POST http://localhost:3333/api/professor
Content-Type: application/json

{"nome": "Alexandro", "cpf": "123.456.235-09", "salario": 1098.98, "localId": 1}

###
GET http://localhost:3333/api/professor

###
GET http://localhost:3333/api/professor/2

###
PUT http://localhost:3333/api/pagamento/edit/1
Content-Type: application/json

{"status": "Pendente"}

### DELETE 
DELETE http://localhost:3333/api/pagamento/1