POST http://localhost:3333/api/aluno
Content-Type: application/json

{ "nome": "Kirk Safado", "nasc": "2023-03-23T16:30:00Z", "localId": 1, "professorId": 1}

###
GET http://localhost:3333/api/aluno

###
GET http://localhost:3333/api/aluno/4

### DELETE 
DELETE http://localhost:3333/api/aluno/5